const ICON_RULES: Array<{ icon: string; pattern: RegExp }> = [
  { icon: "🍇", pattern: /\bgrape(s)?\b/ },
  { icon: "🍈", pattern: /\bmelon\b/ },
  { icon: "🍉", pattern: /\bwatermelon\b/ },
  { icon: "🍊", pattern: /\b(tangerine|mandarin|orange)\b/ },
  { icon: "🍋", pattern: /\blemon\b/ },
  { icon: "🍋‍🟩", pattern: /\blime\b/ },
  { icon: "🍌", pattern: /\bbanana\b/ },
  { icon: "🍍", pattern: /\bpineapple\b/ },
  { icon: "🥭", pattern: /\bmango\b/ },
  { icon: "🍎", pattern: /\b(red apple|apple)\b/ },
  { icon: "🍏", pattern: /\bgreen apple\b/ },
  { icon: "🍐", pattern: /\bpear\b/ },
  { icon: "🍑", pattern: /\bpeach\b/ },
  { icon: "🍒", pattern: /\bcherr(y|ies)\b/ },
  { icon: "🍓", pattern: /\bstrawberry\b/ },
  { icon: "🫐", pattern: /\bblueberr(y|ies)\b/ },
  { icon: "🥝", pattern: /\bkiwi\b/ },
  { icon: "🍅", pattern: /\btomato\b/ },
  { icon: "🫒", pattern: /\bolive\b/ },
  { icon: "🥥", pattern: /\bcoconut\b/ },
  { icon: "🥑", pattern: /\bavocado\b/ },
  { icon: "🍆", pattern: /\b(eggplant|aubergine)\b/ },
  { icon: "🥔", pattern: /\bpotato\b/ },
  { icon: "🥕", pattern: /\bcarrot\b/ },
  { icon: "🌽", pattern: /\b(corn|maize)\b/ },
  { icon: "🌶️", pattern: /\b(hot pepper|chili|chilli)\b/ },
  { icon: "🫑", pattern: /\b(bell pepper|capsicum)\b/ },
  { icon: "🥒", pattern: /\bcucumber\b/ },
  { icon: "🥬", pattern: /\b(leafy green|lettuce|spinach|kale)\b/ },
  { icon: "🥦", pattern: /\bbroccoli\b/ },
  { icon: "🧄", pattern: /\bgarlic\b/ },
  { icon: "🧅", pattern: /\bonion\b/ },
  { icon: "🥜", pattern: /\b(peanut|peanuts)\b/ },
  { icon: "🫘", pattern: /\b(bean|beans|lentil|lentils)\b/ },
  { icon: "🌰", pattern: /\bchestnut\b/ },
  { icon: "🫚", pattern: /\bginger\b/ },
  { icon: "🫛", pattern: /\bpea(s| pod)?\b/ },
  { icon: "🍄‍🟫", pattern: /\b(mushroom|mushrooms)\b/ },
  { icon: "🫜", pattern: /\b(radish|root vegetable)\b/ },
  { icon: "🍞", pattern: /\bbread\b/ },
  { icon: "🥐", pattern: /\bcroissant\b/ },
  { icon: "🥖", pattern: /\bbaguette\b/ },
  { icon: "🫓", pattern: /\b(flatbread|pita|naan|tortilla)\b/ },
  { icon: "🥨", pattern: /\bpretzel\b/ },
  { icon: "🥯", pattern: /\bbagel\b/ },
  { icon: "🥞", pattern: /\bpancake(s)?\b/ },
  { icon: "🧇", pattern: /\bwaffle(s)?\b/ },
  { icon: "🧀", pattern: /\bcheese\b/ },
  { icon: "🍖", pattern: /\b(meat on bone|rib)\b/ },
  { icon: "🍗", pattern: /\b(chicken|poultry leg|drumstick|turkey)\b/ },
  { icon: "🥩", pattern: /\b(steak|beef|pork|meat)\b/ },
  { icon: "🥓", pattern: /\bbacon\b/ },
  { icon: "🍔", pattern: /\b(hamburger|burger)\b/ },
  { icon: "🍟", pattern: /\b(french fries|fries)\b/ },
  { icon: "🍕", pattern: /\bpizza\b/ },
  { icon: "🌭", pattern: /\bhot dog\b/ },
  { icon: "🥪", pattern: /\bsandwich\b/ },
  { icon: "🌮", pattern: /\btaco\b/ },
  { icon: "🌯", pattern: /\bburrito\b/ },
  { icon: "🫔", pattern: /\btamale\b/ },
  { icon: "🥙", pattern: /\b(stuffed flatbread|shawarma|gyro)\b/ },
  { icon: "🧆", pattern: /\bfalafel\b/ },
  { icon: "🥚", pattern: /\begg\b/ },
  { icon: "🍳", pattern: /\b(cooking|fried egg|omelette)\b/ },
  { icon: "🥘", pattern: /\b(shallow pan|paella)\b/ },
  { icon: "🍲", pattern: /\b(stew|pot of food|soup)\b/ },
  { icon: "🫕", pattern: /\bfondue\b/ },
  { icon: "🥣", pattern: /\b(bowl|porridge|oatmeal)\b/ },
  { icon: "🥗", pattern: /\b(salad|green salad)\b/ },
  { icon: "🍿", pattern: /\bpopcorn\b/ },
  { icon: "🧈", pattern: /\bbutter\b/ },
  { icon: "🧂", pattern: /\bsalt\b/ },
  { icon: "🥫", pattern: /\b(canned food|canned|can)\b/ },
  { icon: "🍝", pattern: /\b(spaghetti|pasta|noodle)\b/ },
  { icon: "🍱", pattern: /\bbento\b/ },
  { icon: "🍘", pattern: /\brice cracker\b/ },
  { icon: "🍙", pattern: /\b(rice ball|onigiri)\b/ },
  { icon: "🍚", pattern: /\b(cooked rice|rice)\b/ },
  { icon: "🍛", pattern: /\b(curry rice|curry)\b/ },
  { icon: "🍜", pattern: /\b(steaming bowl|ramen|udon|pho)\b/ },
  { icon: "🍠", pattern: /\b(roasted sweet potato|sweet potato)\b/ },
  { icon: "🍢", pattern: /\b(oden|skewer|kebab)\b/ },
  { icon: "🍣", pattern: /\b(sushi|sashimi)\b/ },
  { icon: "🍤", pattern: /\b(fried shrimp|shrimp)\b/ },
  { icon: "🍥", pattern: /\bfish cake\b/ },
  { icon: "🥮", pattern: /\bmoon cake\b/ },
  { icon: "🍡", pattern: /\bdango\b/ },
  { icon: "🥟", pattern: /\b(dumpling|gyoza)\b/ },
  { icon: "🥠", pattern: /\bfortune cookie\b/ },
  { icon: "🥡", pattern: /\b(takeout box|takeout)\b/ },
  { icon: "🍦", pattern: /\bsoft ice cream\b/ },
  { icon: "🍧", pattern: /\bshaved ice\b/ },
  { icon: "🍨", pattern: /\bice cream\b/ },
  { icon: "🍩", pattern: /\b(doughnut|donut)\b/ },
  { icon: "🍪", pattern: /\bcookie\b/ },
  { icon: "🎂", pattern: /\b(birthday cake|cake)\b/ },
  { icon: "🍰", pattern: /\bshortcake\b/ },
  { icon: "🧁", pattern: /\bcupcake\b/ },
  { icon: "🥧", pattern: /\bpie\b/ },
  { icon: "🍫", pattern: /\b(chocolate|choco)\b/ },
  { icon: "🍬", pattern: /\bcandy\b/ },
  { icon: "🍭", pattern: /\blollipop\b/ },
  { icon: "🍮", pattern: /\bcustard\b/ },
  { icon: "🍯", pattern: /\bhoney\b/ },
  { icon: "🍼", pattern: /\b(baby bottle|formula)\b/ },
  { icon: "🥛", pattern: /\b(milk|glass of milk)\b/ },
  { icon: "☕", pattern: /\b(hot beverage|coffee)\b/ },
  { icon: "🫖", pattern: /\bteapot\b/ },
  { icon: "🍵", pattern: /\b(teacup|tea)\b/ },
  { icon: "🍶", pattern: /\b(sake)\b/ },
  { icon: "🍾", pattern: /\b(champagne|popping cork)\b/ },
  { icon: "🍷", pattern: /\bwine\b/ },
  { icon: "🍸", pattern: /\bcocktail\b/ },
  { icon: "🍹", pattern: /\b(tropical drink|mocktail)\b/ },
  { icon: "🍺", pattern: /\bbeer\b/ },
  { icon: "🍻", pattern: /\b(clinking beer mugs)\b/ },
  { icon: "🥂", pattern: /\b(clinking glasses|toast)\b/ },
  { icon: "🥃", pattern: /\b(whisky|whiskey|tumbler)\b/ },
  { icon: "🫗", pattern: /\b(pouring liquid|pour)\b/ },
  { icon: "🥤", pattern: /\b(cup with straw|soda)\b/ },
  { icon: "🧋", pattern: /\b(bubble tea|boba)\b/ },
  { icon: "🧃", pattern: /\b(juice box|beverage box)\b/ },
  { icon: "🧉", pattern: /\bmate\b/ },
  { icon: "🫙", pattern: /\bjar\b/ },
  { icon: "🏺", pattern: /\bamphora\b/ },
];

export const inferFoodIconFromName = (name: string): string | undefined => {
  const normalized = name.trim().toLowerCase();
  if (!normalized) {
    return undefined;
  }

  for (const rule of ICON_RULES) {
    if (rule.pattern.test(normalized)) {
      return rule.icon;
    }
  }

  return undefined;
};
